company_products/config/routes.rb
Rails.application.routes.draw do

  resources :companies, only: [:index, :update]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :companies
    end
  end

end

company_products/app/models/company.rb
class Company < ActiveRecord::Base
  has_many :products, dependent: :destroy
end

company_products/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company
end

company_products/app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

  def index
    @companies = Company.order("name")
    render json: @companies
  end

  def update
    @company = Company.find params[:id]
    @company.likes += 1
    if @company.save
      head :ok
    else
      render json: { errors: @company.errors.full_messages }
    end
  end
end

company_products/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

company_products/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.order("name ASC")
    respond_to do |format|
      format.html { render }
      format.json { render json: @companies }
    end
  end

  def edit
    render nothing: true
  end

  def update
    @company = Company.find params[:id]
    @company.likes += 1
    if @company.save
      redirect_to companies_path, notice: "Liked!"
    else
      render companies_path, notice: "Unable to like!"
    end
  end
end

company_products/app/helpers/api/v1/companies_helper.rb
module Api::V1::CompaniesHelper
end

company_products/app/helpers/application_helper.rb
module ApplicationHelper
end

company_products/app/helpers/companies_helper.rb
module CompaniesHelper
end

company_products/app/views/companies/index.html.erb
<% @companies.each do |company| %>
<h2><%= company.name %></h2>
<%= link_to "Like", company_path(company), method: :patch %>
<p>Likes: <%= company.likes %></p>
<ul>
  <% company.products.each do |product| %>
    <li><%= product.name %></li>
  <% end %>
</ul>
<% end %>

company_products/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompanyProducts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>